version: '3.8'
services:
  burnitgw: 
    image: burnit:${VERSION}
    container_name: burnit
    ports:
    - "3000:3000"       
    depends_on:
    - database
    env_file:
    - ./.env

  database:
    image: ${DB_IMAGE}
    container_name: ${DB_IMAGE}
    ports:
    - "${DB_PORT}:${DB_PORT}"
